import { useState } from "react";
import {
  AlertTriangle,
  BookOpenCheck,
  Boxes,
  ChevronDown,
  Eye,
  Layers,
  Link2,
  ListChecks,
  Scale,
  Target,
  TrendingDown,
  Trophy,
} from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { cn } from "@/lib/utils";
import {
  FACTOR_PLAIN,
  PENALTY_PLAIN,
  SCORECARD_PLAIN_INTRO,
  scorePlain,
} from "@/lib/serenity/scorecard";
import type {
  ApiAnalysis,
  ComparisonAnalysis,
  SerenityAnalysis,
  ThemeAnalysis,
} from "@/types";

/* ------------------------------------------------------------------------- */
/* Structured (simulated engine) analysis                                    */
/* ------------------------------------------------------------------------- */

const STRENGTH_VARIANT: Record<string, "default" | "accent" | "secondary" | "warning" | "bearish"> = {
  primary: "default",
  media: "accent",
  analysis: "accent",
  social: "warning",
  rumor: "bearish",
};

function Section({
  icon: Icon,
  title,
  children,
}: {
  icon: React.ComponentType<{ className?: string }>;
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section>
      <h4 className="mb-2 flex items-center gap-2 text-xs font-semibold uppercase tracking-wide text-muted-foreground">
        <Icon className="h-3.5 w-3.5" /> {title}
      </h4>
      {children}
    </section>
  );
}

function scoreTone(score: number): string {
  if (score >= 70) return "text-bullish";
  if (score >= 55) return "text-accent";
  return "text-muted-foreground";
}

export function StructuredAnalysis({ analysis }: { analysis: SerenityAnalysis }) {
  return (
    <div className="space-y-5">
      {/* Verdict header */}
      <div className="flex flex-wrap items-center justify-between gap-3 rounded-lg border border-border bg-background/50 p-4">
        <div className="min-w-0">
          <div className="flex flex-wrap items-center gap-2">
            <span className="text-lg font-semibold">${analysis.ticker}</span>
            <span className="min-w-0 break-words text-sm text-muted-foreground">{analysis.companyName}</span>
          </div>
          <div className="mt-1 flex flex-wrap items-center gap-2">
            {analysis.mode === "ai" ? (
              <Badge variant="warning" className="max-w-full whitespace-normal break-all" title={`Generated by ${analysis.ai?.model ?? "an AI model"} — verify before acting`}>
                AI research · {analysis.ai?.model ?? "unverified"}
              </Badge>
            ) : (
              <Badge variant="secondary">Built-in knowledge base</Badge>
            )}
            <span className="text-xs text-muted-foreground">bottleneck scorecard</span>
          </div>
        </div>
        <div className="text-right">
          <div className={cn("text-3xl font-bold tabular-nums", scoreTone(analysis.finalScore))}>
            {analysis.finalScore}
            <span className="text-base font-medium text-muted-foreground">/100</span>
          </div>
          <div className="text-sm font-medium">{analysis.verdict}</div>
        </div>
      </div>

      {/* Plain-language score reading (for non-expert users) */}
      <div className="-mt-2 rounded-md border border-border/50 bg-muted/20 px-3 py-2 text-xs leading-relaxed text-muted-foreground">
        <span className="font-medium text-foreground/80">In plain terms:</span>{" "}
        {scorePlain(analysis.finalScore)} The 0–100 number is a{" "}
        <em>research-priority</em> signal — how much this deserves a closer look — not a
        price target or a buy/sell call.
      </div>

      <Section icon={Target} title="What exactly does it constrain?">
        <p className="text-sm leading-relaxed">{analysis.whatItConstrains}</p>
      </Section>

      <Section icon={Boxes} title="Value-chain breakdown">
        <p className="mb-3 text-sm text-muted-foreground">{analysis.chainPosition}</p>
        <ol className="space-y-1.5">
          {analysis.chain.map((layer) => {
            const isCompany = layer.layer.includes("◀");
            return (
              <li
                key={layer.layer}
                className={cn(
                  "flex items-start justify-between gap-3 rounded-md border px-3 py-2 text-sm",
                  layer.isScarce
                    ? "border-primary/40 bg-primary/5"
                    : "border-border/60 bg-background/30",
                  isCompany && "ring-1 ring-accent/50",
                )}
              >
                <div className="min-w-0">
                  <span className={cn("font-medium", isCompany && "text-accent")}>
                    {layer.layer.replace(" ◀ company", "")}
                  </span>
                  <span className="ml-2 hidden text-xs text-muted-foreground sm:inline">
                    {layer.role}
                  </span>
                </div>
                <div className="flex shrink-0 gap-1.5">
                  {isCompany && <Badge variant="accent">company</Badge>}
                  {layer.isScarce && <Badge>scarce layer</Badge>}
                </div>
              </li>
            );
          })}
        </ol>
      </Section>

      <Section icon={Scale} title="Bottleneck scorecard">
        <p className="mb-3 text-xs leading-relaxed text-muted-foreground">
          {SCORECARD_PLAIN_INTRO}
        </p>
        <div className="mb-1 text-[11px] font-semibold uppercase tracking-wide text-bullish/80">
          Strengths (add to the score)
        </div>
        <div className="grid gap-x-6 gap-y-3 sm:grid-cols-2">
          {analysis.factors.map((f) => (
            <div key={f.key}>
              <div className="mb-0.5 flex items-baseline justify-between gap-2 text-xs">
                <span className="font-medium">{f.label}</span>
                <span className="shrink-0 tabular-nums text-muted-foreground">{f.rating}/5</span>
              </div>
              <p className="mb-1 text-[11px] leading-snug text-muted-foreground">
                {FACTOR_PLAIN[f.key] ?? ""}
                {f.note && <span className="text-foreground/70"> — {f.note}</span>}
              </p>
              <Progress value={(f.rating / 5) * 100} />
            </div>
          ))}
        </div>

        {analysis.penalties.some((p) => p.rating > 0) && (
          <>
            <div className="mb-1.5 mt-4 text-[11px] font-semibold uppercase tracking-wide text-bearish/80">
              Risks (subtract from the score)
            </div>
            <ul className="space-y-1.5">
              {analysis.penalties
                .filter((p) => p.rating > 0)
                .map((p) => (
                  <li key={p.key} className="flex items-start gap-2 text-xs">
                    <Badge variant="bearish" className="mt-0.5 shrink-0">
                      {p.label} −{p.points}
                    </Badge>
                    <span className="text-muted-foreground">{PENALTY_PLAIN[p.key] ?? ""}</span>
                  </li>
                ))}
            </ul>
          </>
        )}

        <p className="mt-3 text-xs tabular-nums text-muted-foreground">
          Strength points {analysis.rawFactorPoints} − risk points {analysis.penaltyPoints} ={" "}
          <span className="font-medium text-foreground">{analysis.finalScore} / 100</span>
        </p>
      </Section>

      <Section icon={Link2} title="Evidence (graded by how solid it is)">
        <p className="mb-2 text-[11px] leading-snug text-muted-foreground">
          Strongest → weakest: <strong>primary</strong> (official filings/contracts) ·{" "}
          <strong>media</strong> (reputable press) · <strong>analysis</strong> (expert
          research) · <strong>social</strong> (posts, tips) · <strong>rumor</strong>{" "}
          (unconfirmed). Anything below “media” still needs checking.
        </p>
        <ul className="space-y-2">
          {analysis.evidence.map((e, i) => (
            <li key={i} className="flex items-start gap-2 text-sm">
              <Badge variant={STRENGTH_VARIANT[e.strength] ?? "secondary"} className="mt-0.5 shrink-0">
                {e.strength}
              </Badge>
              <div className="min-w-0">
                <p className="break-words">{e.claim}</p>
                <p className="break-words text-xs text-muted-foreground">{e.source}</p>
              </div>
            </li>
          ))}
        </ul>
      </Section>

      <Section icon={Eye} title="What the market may be missing">
        <p className="text-sm leading-relaxed">{analysis.marketMayMiss}</p>
      </Section>

      <Section icon={AlertTriangle} title="What could prove this wrong">
        <ul className="list-inside list-disc space-y-1 text-sm">
          {analysis.weakeners.map((w, i) => (
            <li key={i}>{w}</li>
          ))}
        </ul>
      </Section>

      <Section icon={ListChecks} title="Next verification steps">
        <ul className="space-y-1.5 text-sm">
          {analysis.nextChecks.map((c, i) => (
            <li key={i} className="flex items-start gap-2">
              <span className="mt-1 h-1.5 w-1.5 shrink-0 rounded-full bg-primary" />
              {c}
            </li>
          ))}
        </ul>
      </Section>

      <p className="border-t border-border/60 pt-3 text-xs text-muted-foreground">
        Research support only — ranked by research priority, not a buy/sell
        recommendation. The trading decision is yours.{" "}
        {analysis.mode === "ai"
          ? `Generated by ${analysis.ai?.model ?? "an AI model"} from its own knowledge without live web access — every claim is unverified until you check the sources listed above.`
          : "Built from the app's curated knowledge base; verify every claim with the listed primary sources."}
      </p>
    </div>
  );
}

/* ------------------------------------------------------------------------- */
/* Theme-scan view (layers before companies, per SKILL.md)                   */
/* ------------------------------------------------------------------------- */

const SCARCITY_LABEL = ["context", "watch", "tight", "scarce"] as const;
const SCARCITY_VARIANT = ["secondary", "outline", "accent", "default"] as const;

export function ThemeAnalysisView({
  analysis,
  onSelectTicker,
}: {
  analysis: ThemeAnalysis;
  onSelectTicker?: (ticker: string) => void;
}) {
  return (
    <div className="space-y-5">
      <div className="rounded-lg border border-border bg-background/50 p-4">
        <div className="flex flex-wrap items-center gap-2">
          <Layers className="h-4 w-4 shrink-0 text-primary" />
          <span className="min-w-0 break-words text-lg font-semibold">{analysis.title}</span>
        </div>
        <div className="mt-1 flex flex-wrap items-center gap-2">
          <Badge variant="secondary">Theme scan</Badge>
          {analysis.isInitialPass && (
            <Badge variant="warning" title="No live sources in this run — per the skill, treat as an initial pass and verify with the listed source checks">
              initial pass — source checks remain
            </Badge>
          )}
        </div>
      </div>

      <Section icon={Target} title="System change driving the theme">
        <p className="text-sm leading-relaxed">{analysis.systemChange}</p>
      </Section>

      <Section icon={Layers} title="Layers ranked first (scarcest at top)">
        <ol className="space-y-1.5">
          {analysis.layers.map((layer, i) => (
            <li
              key={layer.name}
              className={cn(
                "flex items-start gap-3 rounded-md border px-3 py-2 text-sm",
                layer.scarcity === 3
                  ? "border-primary/40 bg-primary/5"
                  : "border-border/60 bg-background/30",
              )}
            >
              <span className="mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-muted text-[11px] font-semibold text-muted-foreground">
                {i + 1}
              </span>
              <div className="min-w-0 flex-1">
                <div className="flex flex-wrap items-center gap-2">
                  <span className="font-medium">{layer.name}</span>
                  <Badge variant={SCARCITY_VARIANT[layer.scarcity]}>
                    {SCARCITY_LABEL[layer.scarcity]}
                  </Badge>
                </div>
                <p className="text-xs text-muted-foreground">{layer.rationale}</p>
              </div>
            </li>
          ))}
        </ol>
      </Section>

      {analysis.priorities.length > 0 && (
        <Section icon={Trophy} title="Research priority list (not a buy list)">
          <ol className="space-y-2">
            {analysis.priorities.map((p, i) => {
              const Row = onSelectTicker ? "button" : "div";
              return (
                <li key={p.ticker}>
                  <Row
                    {...(onSelectTicker
                      ? { onClick: () => onSelectTicker(p.ticker), type: "button" as const }
                      : {})}
                    className={cn(
                      "w-full rounded-md border border-border/60 bg-background/30 px-3 py-2 text-left",
                      onSelectTicker && "transition-colors hover:border-primary/50 hover:bg-primary/5",
                    )}
                  >
                    <div className="flex flex-wrap items-center gap-2 text-sm">
                      <span className="w-5 text-center font-semibold text-muted-foreground">
                        {i + 1}
                      </span>
                      <span className="font-semibold text-accent">${p.ticker}</span>
                      <span className="min-w-0 break-words text-muted-foreground">{p.name}</span>
                      <span className="ml-auto shrink-0 tabular-nums font-medium">
                        {p.score}
                        <span className="text-xs text-muted-foreground">/100</span>
                      </span>
                      <Badge variant="outline">{p.verdict}</Badge>
                    </div>
                    <p className="mt-1 pl-7 text-xs text-muted-foreground">
                      <span className="text-foreground/70">{p.role}</span> · {p.whyRanked}
                    </p>
                  </Row>
                </li>
              );
            })}
          </ol>
          <p className="mt-2 text-xs text-muted-foreground">
            {onSelectTicker
              ? "Scores from the bottleneck scorecard. Tap any ticker for its full single-company breakdown."
              : "Scores from the bottleneck scorecard against the curated knowledge base."}
          </p>
        </Section>
      )}

      {analysis.popularButLower.length > 0 && (
        <Section icon={TrendingDown} title="Popular, but ranked lower">
          <ul className="space-y-1.5 text-sm">
            {analysis.popularButLower.map((p) => (
              <li key={p.name}>
                <span className="font-medium">{p.name}</span>
                <span className="block text-xs text-muted-foreground">{p.why}</span>
              </li>
            ))}
          </ul>
        </Section>
      )}

      <Section icon={Link2} title="Where the evidence lives">
        <ul className="list-inside list-disc space-y-1 text-sm">
          {analysis.evidencePaths.map((e, i) => (
            <li key={i}>{e}</li>
          ))}
        </ul>
      </Section>

      <Section icon={AlertTriangle} title="What could prove the theme wrong">
        <ul className="list-inside list-disc space-y-1 text-sm">
          {analysis.risks.map((r, i) => (
            <li key={i}>{r}</li>
          ))}
        </ul>
      </Section>

      <Section icon={ListChecks} title="Next research moves">
        <ul className="space-y-1.5 text-sm">
          {analysis.nextChecks.map((c, i) => (
            <li key={i} className="flex items-start gap-2">
              <span className="mt-1 h-1.5 w-1.5 shrink-0 rounded-full bg-primary" />
              {c}
            </li>
          ))}
        </ul>
      </Section>

      {analysis.note && (
        <p className="text-xs text-muted-foreground">{analysis.note}</p>
      )}
      <p className="border-t border-border/60 pt-3 text-xs text-muted-foreground">
        Research support only — ranked research priorities, never buy/sell advice.
        Verify every claim through the listed source paths before acting.
      </p>
    </div>
  );
}

/* ------------------------------------------------------------------------- */
/* Candidate-comparison view                                                 */
/* ------------------------------------------------------------------------- */

export function ComparisonView({ analysis }: { analysis: ComparisonAnalysis }) {
  const [open, setOpen] = useState<string | null>(analysis.ranked[0]?.ticker ?? null);
  return (
    <div className="space-y-4">
      <div className="rounded-lg border border-border bg-background/50 p-4">
        <div className="flex flex-wrap items-center gap-2">
          <Trophy className="h-4 w-4 text-primary" />
          <span className="text-lg font-semibold">
            Candidate comparison ({analysis.ranked.length})
          </span>
          <Badge variant="secondary">ranked by bottleneck score</Badge>
        </div>
      </div>

      <ol className="space-y-2">
        {analysis.ranked.map((a, i) => {
          const expanded = open === a.ticker;
          return (
            <li
              key={a.ticker}
              className={cn(
                "overflow-hidden rounded-lg border",
                expanded ? "border-primary/40" : "border-border/60",
              )}
            >
              <button
                onClick={() => setOpen(expanded ? null : a.ticker)}
                className="flex w-full items-center gap-3 px-3 py-2.5 text-left hover:bg-muted/30"
                aria-expanded={expanded}
              >
                <span className="w-5 text-center font-semibold text-muted-foreground">
                  {i + 1}
                </span>
                <span className="font-semibold text-accent">${a.ticker}</span>
                <span className="hidden truncate text-sm text-muted-foreground sm:block">
                  {a.companyName}
                </span>
                <span className="ml-auto tabular-nums font-medium">
                  {a.finalScore}
                  <span className="text-xs text-muted-foreground">/100</span>
                </span>
                <Badge variant="outline" className="hidden sm:inline-flex">
                  {a.verdict}
                </Badge>
                <ChevronDown
                  className={cn(
                    "h-4 w-4 text-muted-foreground transition-transform",
                    expanded && "rotate-180",
                  )}
                />
              </button>
              {expanded && (
                <div className="border-t border-border/60 p-3 sm:p-4">
                  <StructuredAnalysis analysis={a} />
                </div>
              )}
            </li>
          );
        })}
      </ol>
    </div>
  );
}

/* ------------------------------------------------------------------------- */
/* Claude-API (markdown) analysis                                            */
/* ------------------------------------------------------------------------- */

/** Tiny markdown renderer (headings, bold, lists, paragraphs) — no deps. */
function renderMarkdown(md: string): React.ReactNode[] {
  const lines = md.split("\n");
  const out: React.ReactNode[] = [];
  let list: string[] = [];
  const flushList = (key: number) => {
    if (list.length) {
      out.push(
        <ul key={`ul-${key}`} className="mb-3 list-inside list-disc space-y-1 text-sm">
          {list.map((item, i) => (
            <li key={i}>{inline(item)}</li>
          ))}
        </ul>,
      );
      list = [];
    }
  };
  const inline = (s: string): React.ReactNode[] =>
    s.split(/(\*\*[^*]+\*\*)/g).map((part, i) =>
      part.startsWith("**") && part.endsWith("**") ? (
        <strong key={i}>{part.slice(2, -2)}</strong>
      ) : (
        <span key={i}>{part}</span>
      ),
    );

  lines.forEach((line, i) => {
    const h = line.match(/^(#{1,4})\s+(.*)/);
    if (h) {
      flushList(i);
      const level = h[1].length;
      out.push(
        <h4
          key={i}
          className={cn(
            "mb-2 mt-4 font-semibold",
            level <= 2 ? "text-base" : "text-sm uppercase tracking-wide text-muted-foreground",
          )}
        >
          {inline(h[2])}
        </h4>,
      );
    } else if (/^\s*[-*]\s+/.test(line)) {
      list.push(line.replace(/^\s*[-*]\s+/, ""));
    } else if (line.trim() === "") {
      flushList(i);
    } else {
      flushList(i);
      out.push(
        <p key={i} className="mb-2 text-sm leading-relaxed">
          {inline(line)}
        </p>,
      );
    }
  });
  flushList(lines.length);
  return out;
}

export function ApiAnalysisView({ analysis }: { analysis: ApiAnalysis }) {
  return (
    <div>
      <div className="mb-4 flex flex-wrap items-center gap-2">
        <Badge className="gap-1">
          <BookOpenCheck className="h-3 w-3" /> Claude API · Serenity Skill
        </Badge>
        <span className="text-xs text-muted-foreground">
          {analysis.model} · {new Date(analysis.generatedAt).toLocaleString()}
        </span>
      </div>
      <div className="break-words">{renderMarkdown(analysis.markdown)}</div>
      <p className="mt-4 border-t border-border/60 pt-3 text-xs text-muted-foreground">
        Generated by Claude running the bundled Serenity Skill. Research support
        only; verify primary sources before acting.
      </p>
    </div>
  );
}
