// Shared data-model types. These mirror the JSON produced by scripts/process.mjs
// and scripts/analyze.mjs.

export type SentimentLabel = "bullish" | "bearish" | "neutral";

export interface TweetStats {
  replies: number;
  reposts: number;
  likes: number;
  views: number;
}

export interface Mention {
  tweetId: string;
  ticker: string;
  text: string;
  createdAt: string;
  url: string;
  stats: TweetStats;
  sentiment: { score: number; label: SentimentLabel };
}

export interface TickerHistoryPoint {
  date: string;
  count: number;
  avgSentiment: number;
}

export interface TickerAggregate {
  ticker: string;
  count: number;
  firstSeen: string;
  lastSeen: string;
  avgSentiment: number;
  sentimentLabel: SentimentLabel;
  engagement: number;
  history: TickerHistoryPoint[];
}

export interface Digest {
  date: string | null;
  window: { from: string | null; to: string | null };
  totalMentions: number;
  topTickers: { ticker: string; count: number }[];
  newTickers: string[];
}

export interface MentionsData {
  updatedAt: string;
  isSample: boolean;
  handle: string;
  totalTweets: number;
  totalMentions: number;
  mentions: Mention[];
  tickers: TickerAggregate[];
  digest: Digest;
}

/** Precomputed Claude-API analysis stored in analyses.json (optional). */
export interface ApiAnalysis {
  ticker: string;
  generatedAt: string;
  engine: "claude-api";
  model: string;
  markdown: string;
}

export interface AnalysesData {
  updatedAt: string;
  analyses: Record<string, ApiAnalysis>;
}

/* ------------------------- Serenity Skill engine output ------------------ */

export interface ChainLayer {
  layer: string;
  role: string;
  isScarce: boolean;
}

export interface FactorScore {
  key: string;
  label: string;
  rating: number; // 0-5
  weight: number;
  points: number;
  note: string;
}

export interface PenaltyScore {
  key: string;
  label: string;
  rating: number; // 0-5
  points: number;
}

export interface EvidenceItem {
  claim: string;
  source: string;
  strength: "primary" | "media" | "analysis" | "social" | "rumor";
}

export interface ThemeLayer {
  name: string;
  rationale: string;
  scarcity: 0 | 1 | 2 | 3; // 3 = tightest
}

export interface ThemePriority {
  ticker: string;
  name: string;
  role: string; // controls / supplies / benefits / story
  whyRanked: string;
  score: number;
  verdict: string;
}

/** Theme-scan output (SKILL.md "theme scan" mode: layers before companies). */
export interface ThemeAnalysis {
  kind: "theme";
  query: string;
  title: string;
  generatedAt: string;
  isInitialPass: boolean; // no live tools → always labeled per the skill
  systemChange: string;
  layers: ThemeLayer[]; // ranked, scarcest first
  priorities: ThemePriority[]; // ranked candidates
  popularButLower: { name: string; why: string }[];
  evidencePaths: string[];
  risks: string[];
  nextChecks: string[];
  note?: string;
  ai?: AiMeta;
}

/** Candidate-comparison output (SKILL.md "candidate comparison" mode). */
export interface ComparisonAnalysis {
  kind: "comparison";
  query: string;
  generatedAt: string;
  ranked: SerenityAnalysis[]; // sorted by finalScore desc
}

export type AnalysisResult =
  | (SerenityAnalysis & { kind?: "ticker" })
  | ComparisonAnalysis
  | ThemeAnalysis;

/** Entry persisted to localStorage for the history list. */
export interface StoredAnalysis {
  id: string;
  query: string;
  kind: "ticker" | "comparison" | "theme";
  label: string;
  createdAt: string;
  result: AnalysisResult;
}

/** Attribution for analyses generated by a user-configured LLM (BYOK). */
export interface AiMeta {
  provider: string; // free-text label of the endpoint/protocol used
  model: string;
}

export interface SerenityAnalysis {
  ticker: string;
  companyName: string;
  generatedAt: string;
  mode: "simulated" | "ai";
  ai?: AiMeta;
  whatItConstrains: string;
  chainPosition: string;
  chain: ChainLayer[];
  scarceLayers: string[];
  factors: FactorScore[];
  penalties: PenaltyScore[];
  rawFactorPoints: number;
  penaltyPoints: number;
  finalScore: number;
  verdict: string;
  marketMayMiss: string;
  evidence: EvidenceItem[];
  weakeners: string[];
  nextChecks: string[];
}
